version: 2.1

jobs:
  install:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python -m unittest discover tests

  deploy:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install Google Cloud SDK
          command: |
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update
            sudo apt-get install -y google-cloud-sdk

      - run:
          name: Set up GCloud authentication
          command: |
            if [ -z "$IND_KC_GCLOUD_KEY" ]; then
              echo "Error: IND_KC_GCLOUD_KEY is not set."
              exit 1
            fi
            echo $IND_KC_GCLOUD_KEY | base64 --decode > ${HOME}/gcloud-service-key.json || { echo "Failed to decode IND_KC_GCLOUD_KEY"; exit 1; }
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json || { echo "Failed to authenticate with GCloud"; exit 1; }
            gcloud config set project kc-qa-project || { echo "Failed to set GCloud project"; exit 1; }

      - run:
          name: Install Firebase CLI
          command: |
            curl -sL https://firebase.tools | bash

      - run:
          name: Debug Firebase Token
          command: |
            echo "FIREBASE_TOKEN is set."

      - run:
          name: Deploy to Firebase
          command: |
            firebase deploy --token $FIREBASE_TOKEN --only hosting

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install
      - test
      - deploy:
          requires:
            - test
