version: 2.1

jobs:
  install:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Create Virtual Environment and Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip  # Ensure pip is up to date
            pip install -r requirements.txt  # Install requirements

  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip  # Ensure pip is up to date
            pip install -r requirements.txt  # Install requirements
            python -m unittest discover tests  # Discover and run tests

  deploy:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Set up GCloud authentication
          command: |
            echo $IND_KC_GCLOUD_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project kc-qa-project

      - run:
          name: Install Firebase CLI
          command: |
            curl -sL https://firebase.tools | bash

      - run:
          name: Deploy to Firebase
          command: |
            firebase deploy --token $FIREBASE_TOKEN --only hosting

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install
      - test:
          requires:
            - install  # Ensure install job is complete before testing
      - deploy:
          requires:
            - test  # Ensure tests pass before deployment
