version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      # Install Google Cloud SDK
      - run:
          name: Install Google Cloud SDK
          command: |
            sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            sudo apt-get install -y curl
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg
            sudo apt-get update && sudo apt-get install -y google-cloud-sdk

      # Set up GCloud authentication using your service account
      - run:
          name: Set up GCloud authentication
          command: |
            echo $IND_KC_GCLOUD_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project kc-qa-project

      # Install Firebase CLI (if not installed already)
      - run:
          name: Install Firebase CLI
          command: |
            curl -sL https://firebase.tools | bash

      # Deploy to Firebase Hosting or any other Firebase service
      - run:
          name: Firebase Deploy
          command: |
            firebase deploy --token "$(gcloud auth print-access-token)"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
